
services:

    web:
        image: nginx:1.25.2-alpine3.18
        container_name: appname_web
        ports:
            - "8888:80"
        volumes:
            - ./docker/conf.d:/etc/nginx/conf.d
            - ./app:/app
        depends_on:
            - php
        restart: always
        networks:
            - appnamenet

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: appname_php
        environment:
            - DB_HOST=mysql
            - DB_NAME=appname
            - DB_USER=user
            - DB_PASS=password
        volumes:
            - ./app:/app:app
        depends_on:
            - mysql
        restart: always
        networks:
            - appnamenet

    mysql:
        image: mariadb:11.1.2-jammy
        container_name: appname_db
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USERNAME: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'appname'
        volumes:
            - ./docker/db/config/:/etc/mysql/conf.d
            - ./docker/db:/docker-entrypoint-initdb.d
        ports:
            - "3325:3306"
        restart: always
        healthcheck:
          test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USERNAME --password=$$MYSQL_PASSWORD
        networks:
            - appnamenet

volumes:
   appname: {}

networks:
    appnamenet: {}
        
