services:
  web:
    image: nginx:1.25.2-alpine3.18
    ports:
      - "8888:80"
    volumes:
      - ./docker/conf.d:/etc/nginx/conf.d:ro
      - ./app:/app
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - appnamenet

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      DB_HOST: mysql
      DB_NAME: appname
      DB_USER: user
      DB_PASS: password
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - appnamenet

  mysql:
    image: mariadb:11.1.2-jammy
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appname
    volumes:
      - ./docker/db/config:/etc/mysql/conf.d:ro
      - ./docker/db:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
    ports:
      - "3325:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - appnamenet

volumes:
  mysql_data:

networks:
  appnamenet:
